groups:
- name: all
  jobs:
  - blackbox-deploy
  - cf-blackbox-tests
  - cf-blackbox-group-tests
  - deploy-datadog-forwarder

resources:
- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master
    private_key: {{loggregator-key}}

- name: deployments-loggregator
  type: git
  source: &deployments_loggregator
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    branch: v6.5

- name: loggregator-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-release.git
    branch: release-elect
    private_key: {{loggregator-key}}
    ignore_paths:
    - .final_builds
    - releases

- name: log-cache-acceptance-tests-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/log-cache-acceptance-tests-release
    branch: master

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: loggregator-ci-docker-images
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}
    paths:
    - docker-images

- name: loggregator-tools
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/loggregator-tools.git
    branch: master
    private_key: {{loggregator-key}}

- name: nozzle-image
  type: docker-image
  source:
    repository: loggregator/log-cache-nozzle
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: gateway-image
  type: docker-image
  source:
    repository: loggregator/log-cache-gateway
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: loggregator-agent-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-agent-release.git
    branch: develop
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: log-cache-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: develop
    private_key: {{cf-loggregator-oauth-bot-key}}
    ignore_paths:
    - .final_builds
    - releases
    disable_ci_skip: false

- name: log-cache-release-elect
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: release-elect
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: log-cache-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}
    disable_ci_skip: true

- name: log-cache
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: go-log-cache
  type: git
  source:
    uri: https://github.com/cloudfoundry/go-log-cache
    branch: master

- name: go-loggregator
  type: git
  source:
    uri: https://github.com/cloudfoundry/go-loggregator
    branch: master

- name: log-cache-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/log-cache-cli
    branch: develop

- name: log-cache-cli-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-cli
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: bumper-tool
  type: git
  source:
    uri: https://github.com/loggregator/bumper

- name: leadership-election
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/leadership-election

- name: leadership-election-release
  type: git
  source:
    branch: develop
    ignore_paths:
    - .final_builds
    - releases
    private_key: {{cf-loggregator-oauth-bot-key}}
    uri: git@github.com:cloudfoundry/leadership-election-release

- name: log-cache-image
  type: docker-image
  source:
    repository: loggregator/log-cache
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: scheduler-image
  type: docker-image
  source:
    repository: loggregator/log-cache-scheduler
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: blackbox-deploy
  serial: true
  plan:
  - aggregate:
    - get: deployments-loggregator
    - get: log-cache-release
      passed:
      - cf-deploy
      trigger: true
    - get: loggregator-ci
  - task: create-blackbox-ops-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: v3.19.0
      outputs:
      - name: ops-files
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          set -e

          cat <<EOT >> ops-files/blackbox.yml
          - type: replace
            path: /name
            value: blackbox
          - type: replace
            path: /instance_groups
            value:
            - name: blackbox
              azs: [z1]
              instances: 1
              persistent_disk_type: 5GB
              vm_type: minimal
              stemcell: default
              networks: [{name: default}]
              jobs:
              - name: log-cache-blackbox
                release: log-cache
                consumes:
                  log-cache: {from: log-cache, deployment: cf}
                properties:
                  log_cache_host: doppler.service.cf.internal
                  datadog:
                    api_key: ((datadog-loggregator-api-key))
                    tags: [blackbox]
                    origin_host: lime.loggr.cf-app.com
                consumes: {log-cache: {from: log-cache, deployment: cf}}
          EOT

  - task: blackbox-deploy
    file: loggregator-ci/tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: gcp/lime
      DEPLOYMENT_NAME: blackbox
      MANIFEST_FILE: manifests/log-cache-blackbox.yml
      OPS_FILES: |
        blackbox.yml
      VARS_FILES: gcp/lime/deployment-vars.yml
      VARS_STORE_FILE: gcp/lime/blackbox-vars.yml
    input_mapping:
      bbl-state: deployments-loggregator
      bosh-release: log-cache-release
      ops-files: ops-files
      vars-files: deployments-loggregator
      vars-store: deployments-loggregator

- name: cf-blackbox-tests
  public: false
  serial_groups: [live-tests]
  serial: true
  plan:
  - aggregate:
    - get: loggregator-tools
    - get: loggregator-ci
    - get: 10m
      trigger: true
  - aggregate:
    - task: push-request-spinner
      file: loggregator-ci/tasks/log-cache-request-spinner-push/task.yml
      timeout: 15m
      params:
        APP_NAME: "request-spinner"
        SYSTEM_DOMAIN: "lime.loggr.cf-app.com"
        LOG_CACHE_ADDR: http://log-cache.lime.loggr.cf-app.com
        ORG: test
        SPACE: test
        USERNAME: admin
        PASSWORD: {{cf_admin_password}}
        SKIP_SSL_VALIDATION: true
        UAA_CLIENT: blackbox
        UAA_CLIENT_SECRET: {{blackbox_client_secret}}
    - task: push-log-cache-siege
      file: loggregator-ci/tasks/log-cache-siege-push/task.yml
      timeout: 15m
      params:
        APP_NAME: "log-cache-siege"
        SYSTEM_DOMAIN: "lime.loggr.cf-app.com"
        LOG_CACHE_ADDR: http://log-cache.lime.loggr.cf-app.com
        REQUEST_SPINNER_ADDR: http://request-spinner.lime.loggr.cf-app.com
        ORG: test
        SPACE: test
        USERNAME: admin
        PASSWORD: {{cf_admin_password}}
        SKIP_SSL_VALIDATION: true
        UAA_CLIENT: blackbox
        UAA_CLIENT_SECRET: {{blackbox_client_secret}}
  # Note: all log-cache testing tasks should run serially to prevent test
  # result pollution
  - task: log-cache-blackbox-tests
    file: loggregator-ci/tasks/cf-log-cache-blackbox/task.yml
    timeout: 15m
    params:
      APP_NAME: "log-cache-blackbox"
      APP_ADDR: "log-cache-blackbox.lime.loggr.cf-app.com"
      SYSTEM_DOMAIN: "lime.loggr.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOG_CACHE_URL: http://log-cache.lime.loggr.cf-app.com
      ORG: test
      SPACE: test
      USERNAME: admin
      PASSWORD: {{cf_admin_password}}
      SKIP_SSL_VALIDATION: true
      UAA_CLIENT: blackbox
      UAA_CLIENT_SECRET: {{blackbox_client_secret}}
  - task: log-cache-siege
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      params:
        LOG_CACHE_SIEGE_ADDR: http://log-cache-siege.lime.loggr.cf-app.com
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -ex
          curl -d '' -X POST $LOG_CACHE_SIEGE_ADDR/v1/siege

- name: cf-blackbox-group-tests
  public: false
  serial_groups: [live-tests]
  serial: true
  plan:
  - aggregate:
    - get: loggregator-tools
    - get: loggregator-ci
    - get: 10m
      trigger: true
  - aggregate:
    - task: push-request-spinner
      file: loggregator-ci/tasks/log-cache-request-spinner-push/task.yml
      timeout: 15m
      params:
        APP_NAME: "request-spinner"
        SYSTEM_DOMAIN: "lime.loggr.cf-app.com"
        LOG_CACHE_ADDR: http://log-cache.lime.loggr.cf-app.com
        ORG: test
        SPACE: test
        USERNAME: admin
        PASSWORD: {{cf_admin_password}}
        SKIP_SSL_VALIDATION: true
        UAA_CLIENT: blackbox
        UAA_CLIENT_SECRET: {{blackbox_client_secret}}
  - task: log-cache-group-blackbox-tests
    file: loggregator-ci/tasks/log-cache-group-blackbox/task.yml
    timeout: 15m
    params:
      APP_NAME: "log-cache-blackbox-groups"
      APP_ADDR: "log-cache-blackbox-groups.lime.loggr.cf-app.com"
      SYSTEM_DOMAIN: "lime.loggr.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOG_CACHE_URL: http://log-cache.lime.loggr.cf-app.com
      ORG: test
      SPACE: test
      USERNAME: admin
      PASSWORD: {{cf_admin_password}}
      SKIP_SSL_VALIDATION: true
      UAA_CLIENT: blackbox
      UAA_CLIENT_SECRET: {{blackbox_client_secret}}

- name: deploy-datadog-forwarder
  public: false
  serial: true
  plan:
  - aggregate:
    - get: loggregator-tools
    - get: loggregator-ci
  - task: deploy-datadog-forwarder
    file: loggregator-ci/tasks/datadog-forwarder/task.yml
    timeout: 15m
    params:
      APP_NAME: "datadog-forwarder"
      SYSTEM_DOMAIN: "lime.loggr.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DATADOG_TAGS: accumulator-lime
      ORG: test
      SPACE: test
      USERNAME: admin
      PASSWORD: {{cf_admin_password}}
      LOG_CACHE_HTTP_ADDR: https://log-cache.lime.loggr.cf-app.com
      LOG_CACHE_GROUP_NAME: lime-datadog-forwarder
      SKIP_SSL_VALIDATION: true
      UAA_CLIENT: datadog-forwarder
      UAA_CLIENT_SECRET: ((datadog_forwarder_client_secret))
