---
platform: linux

inputs:
  - name: baked-tile
  - name: gcp-light-stemcell
  - name: tile-version
  - name: log-cache-ci
  - name: loggregator-agent-dev-release
  - name: environment
    optional: true

outputs:
  - name: environment

PARAMS:
  TOOLSMITHS_ENV_JSON: ""

run:
  path: log-cache-ci/tasks/tile_install/task
