---
platform: linux

inputs:
  - name: baked-tile
  - name: gcp-light-stemcell
  - name: tile-version
  - name: log-cache-ci

PARAMS:
  TOOLSMITHS_ENV:

run:
  path: log-cache-ci/tasks/tile_install/task
