---
platform: linux

inputs:
  - name: environment
  - name: deployment-tools
  - name: log-cache-ci
  - name: tile-config
    optional: true
  - name: tile-version
  - name: baked-tile

params:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
  STEMCELL_URL:
  STEMCELL_SHA:
  PRODUCT_CONFIG_PATH:

run:
  path: log-cache-ci/tasks/tile_install/task
