platform: linux

image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
- name: log-cache-ci
- name: slack-rate-limit-version
  optional: true

outputs:
- name: metadata

run:
  path: log-cache-ci/tasks/alert-message-create/task

params:
  TITLE:
