image_resource:
  type: docker-image
  source:
    repository: logcache/base
platform: linux

inputs:
- name: version
- name: log-cache-ci

outputs:
- name: messages

run:
  path: log-cache-ci/tasks/alert-message-release/task

params:
  LEVEL:
