---
platform: linux
image_resource: ((cf_tasks_image_resource))

inputs:
- name: log-cache-ci
- name: release-repo

outputs:
- name: committed-repo

run:
  path: ../log-cache-ci/tasks/commit/task
  dir: committed-repo

params:
  # - Required.
  # - The commit message.
  COMMIT_MESSAGE:
