---
platform: linux

inputs:
  - name: log-cache-ci
  - name: tile-version
  - name: metric-store-dev-release
  - name: metric-store-release
  - name: oss-metric-store-release
  - name: stemcell
  - name: bpm-release
  - name: cf-routing-release
  - name: loggregator-agent-release

outputs:
  - name: baked-tile
  - name: new-tile-version
  - name: bpm-release
  - name: cf-routing-release
  - name: loggregator-agent-release

params:
  TILE_NAME: app-metric-store

run:
  path: log-cache-ci/tasks/tile_bake/task
