resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.20.0

- name: log-cache-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: develop
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: log-cache-deployments
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-deployments
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: log-cache-version
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache
    access_key_id: ((release-credentials.yml/Notes/loggregator-team-s3-access-key))
    secret_access_key: ((release-credentials.yml/Notes/loggregator-team-s3-secret-key))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-ci.yml/Notes/slack_alert_webhook_url))

jobs:
- name: log-cache-edge-deploy
  plan:
  - put: slack-alert
    params:
      silent: true
      username: ((slack-ci.yml/Notes/slack_alert_username))
      icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
      channel: ((slack-ci.yml/Notes/slack_alert_channel))
      text: ":yellow_heart: Started :tree-log::dollar: Log Cache deployment to :knife: PWS Edge"
  - aggregate:
    - get: cf-deployment-concourse-tasks-image
    - get: log-cache-release
    - get: log-cache-deployments
    - get: log-cache-version
      params: {pre: dev}
  - task: upload-log-cache
    image: cf-deployment-concourse-tasks-image
    config:
      platform: linux
      params:
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          pushd log-cache-release
            cp ../log-cache-version/version src/
            bosh create-release --force
            bosh upload-release --rebase
          popd
      inputs:
      - name: log-cache-release
      - name: log-cache-version
  - task: log-cache-edge-deploy
    image: cf-deployment-concourse-tasks-image
    config:
      platform: linux
      params:
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
        DEPLOYMENT_NAME: log-cache-edge
        MANIFEST_FILE: manifests/log-cache.yml
        SECRETS_FILE: shared-secrets.yml
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          bosh \
            interpolate "log-cache-release/$MANIFEST_FILE" \
            --ops-file "log-cache-deployments/pws/edge/log-cache-edge-ops-file.yml"

          bosh \
            deploy "log-cache-release/$MANIFEST_FILE" \
            --deployment "$DEPLOYMENT_NAME" \
            --non-interactive \
            --ops-file "log-cache-deployments/pws/edge/log-cache-edge-ops-file.yml"
      inputs:
      - name: log-cache-release
      - name: log-cache-deployments
  - put: log-cache-version
    params: {file: log-cache-version/version}
  on_success:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text: ":green_heart: Finished :tree-log::dollar: Log Cache deployment to :knife: PWS Edge"
  on_failure:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text: ":broken_heart: Failed to deploy :tree-log::dollar: Log Cache: to :knife: PWS Edge
          Details here: https://log-cache.ci.cf-app.com/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
