resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.24.0

- name: metric-store-release
  type: git
  source:
    uri: git@github.com:pivotal/metric-store-release
    branch: develop
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: log-cache-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-ci
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: log-cache-deployments
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-deployments
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-ci.yml/Notes/slack_alert_webhook_url))

- name: nightly
  type: time
  source:
    interval: 24h
    start: 6 AM
    stop: 7 AM
    location: America/Denver

- name: every-23-hours
  type: time
  source:
    interval: 23h

jobs:
- name: metric-store-edge-deploy
  plan:
  - put: slack-alert
    params:
      silent: true
      username: ((slack-ci.yml/Notes/slack_alert_username))
      icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
      channel: ((slack-ci.yml/Notes/slack_alert_channel))
      text: ":yellow_heart: Started :metric: Metric Store deployment to :knife: PWS Edge"
  - aggregate:
    - get: cf-deployment-concourse-tasks-image
    - get: metric-store-release
    - get: log-cache-ci
    - get: log-cache-deployments
      params: {pre: dev}
  - task: upload-metric-store
    file: log-cache-ci/tasks/upload-release/task.yml
    image: cf-deployment-concourse-tasks-image
    input_mapping:
      bosh-release-dir: metric-store-release
    params:
      BOSH_CA_CERT: ((bosh-ca-cert.certificate))
      BOSH_CLIENT: ((bosh-admin-client.username))
      BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
      BOSH_ENVIRONMENT: bosh.run.pivotal.io
      JSON_KEY: ((release-credentials.yml/Notes/gcp-service-account-key))
      FORCE: true
  - task: deploy
    image: cf-deployment-concourse-tasks-image
    config:
      platform: linux
      params:
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
        BOSH_DEPLOYMENT: metric-store-edge
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          bosh \
            deploy "log-cache-deployments/pws/edge/metric-store-edge-manifest.yml" \
            --non-interactive
      inputs:
      - name: log-cache-deployments
  on_success:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text: ":green_heart: Finished :metric: Metric Store deployment to :knife: PWS Edge"
  on_failure:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text: ":broken_heart: Failed to deploy :metric: Metric Store: to :knife: PWS Edge
          Details here: https://log-cache.ci.cf-app.com/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: metric-store-edge-nightly-redeploy
  serial_groups: [chaos]
  plan:
  - put: slack-alert
    params:
      silent: true
      username: ((slack-ci.yml/Notes/slack_alert_username))
      icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
      channel: ((slack-ci.yml/Notes/slack_alert_channel))
      text: ":monkey: Starting nightly :metric: Metric Store Edge redeployment"
  - aggregate:
    - get: cf-deployment-concourse-tasks-image
    - get: metric-store-release
      passed: [metric-store-edge-deploy]
    - get: nightly
      trigger: true
  - task: redeploy
    image: cf-deployment-concourse-tasks-image
    config:
      platform: linux
      params:
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
        BOSH_DEPLOYMENT: metric-store-edge
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          bosh manifest > manifest.yml
          bosh deploy --non-interactive --recreate manifest.yml
  on_success:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text: ":green_heart: Finished nightly :metric: Metric Store Edge redeployment"
  on_failure:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text: ":broken_heart: Failed nightly :metric: Metric Store Edge redeployment
          Details here: https://log-cache.ci.cf-app.com/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: metric-store-edge-kill-vm
  serial_groups: [chaos]
  plan:
  - put: slack-alert
    params:
      silent: true
      username: ((slack-ci.yml/Notes/slack_alert_username))
      icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
      channel: ((slack-ci.yml/Notes/slack_alert_channel))
      text: ":monkey: Killing a :metric: Metric Store Edge vm"
  - aggregate:
    - get: cf-deployment-concourse-tasks-image
    - get: metric-store-release
      passed: [metric-store-edge-deploy]
    - get: every-23-hours
      trigger: true
  - task: kill-vm
    image: cf-deployment-concourse-tasks-image
    config:
      platform: linux
      params:
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
        BOSH_DEPLOYMENT: metric-store-edge
        VM_OFFLINE_DURATION: 5m
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          vm_to_stop="$(bosh vms |
            grep 'metric-store/' |
            sort -R |
            head -n 1 |
            awk '{print $1}')"

          bosh \
            stop "${vm_to_stop}" \
            --soft --skip-drain \
            --non-interactive

          sleep ${VM_OFFLINE_DURATION}

          bosh \
            start "${vm_to_stop}" \
            --non-interactive
  on_success:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text: ":green_heart: Finished killing and restarting a :metric: Metric Store Edge vm"
  on_failure:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text: ":broken_heart: Failed to kill a :metric: Metric Store Edge vm
          Details here: https://log-cache.ci.cf-app.com/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
