image_resource:
  type: docker-image
  source:
    repository: logcache/base
platform: linux

inputs:
- name: release-version
- name: release-tarball
- name: log-cache-ci

outputs:
- name: github-release

run:
  path: log-cache-ci/tasks/publish-github-release/task

params:
  PROJECT_NAME:
