product-name: p-metric-store
network-properties:
  network:
    name: <%= toolsmiths_env_name %>-pas-subnet
  other_availability_zones:
    - name: us-central1-a
    - name: us-central1-b
    - name: us-central1-c
  singleton_availability_zone:
    name: us-central1-a
