platform: linux
image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
- name: bbl-state
- name: cf-deployment-concourse-tasks
- name: log-cache-release-version
- name: log-cache-deployments
- name: log-cache-ci

outputs:
- name: log-cache-deployments-modified

params:
  BBL_STATE_DIR:

run:
  path: log-cache-ci/tasks/snapshot-acceptance-environment/task
