image_resource:
  type: docker-image
  source:
    repository: logcache/base
platform: linux
inputs:
  - name: bbl-state
  - name: log-cache-ci
params:
  BBL_STATE_DIR:
  ORG:
  SPACE:
  SYSTEM_DOMAIN:
run:
  path: log-cache-ci/tasks/create-org-and-space/task
