platform: linux
image_resource: ((cf_tasks_image_resource))
inputs:
  - name: bbl-state
  - name: cf-deployment-concourse-tasks
  - name: log-cache-ci
params:
  BBL_STATE_DIR:
  ORG:
  SPACE:
  SYSTEM_DOMAIN:
run:
  path: log-cache-ci/tasks/create-org-and-space/task
