resources:
- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator
    private_key: ((deployments_loggregator_key.private_key))

- name: log-cache-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/log-cache-release
    branch: develop

jobs:
- name: log-cache-blackbox-deploy
  serial: true
  plan:
  - aggregate:
    - get: deployments-loggregator
    - get: log-cache-release
      trigger: true

  - aggregate:
    - task: upload-log-cache
      config:
        image_resource:
          type: docker-image
          source:
            repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
        platform: linux
        inputs:
        - name: log-cache-release
        params:
          BOSH_CLIENT: ((prod_bosh_client_id))
          BOSH_CLIENT_SECRET: ((prod_bosh_client_secret))
          BOSH_CA_CERT: ((prod_bosh_ca_cert))
          BOSH_ENVIRONMENT: ((prod_bosh_target))
        run:
          path: bash
          args:
          - -c
          - |
            #!/bin/bash
            set -eux

            pushd log-cache-release
              bosh create-release
              bosh upload-release --rebase
            popd

  - task: log-cache-blackbox-deploy
    config:
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      platform: linux
      inputs:
      - name: log-cache-release
      - name: deployments-loggregator
      params:
        DEPLOYMENT_NAME: log-cache-blackbox
        MANIFEST_FILE: manifests/log-cache-blackbox.yml
        SECRETS_FILE: shared-secrets.yml
        BOSH_CLIENT: ((prod_bosh_client_id))
        BOSH_CLIENT_SECRET: ((prod_bosh_client_secret))
        BOSH_CA_CERT: ((prod_bosh_ca_cert))
        BOSH_ENVIRONMENT: ((prod_bosh_target))
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          cat <<EOF >pws.yml
          - type: replace
            path: /instance_groups/name=log-cache-blackbox/azs
            value: [z2, z3, z4]
          - type: replace
            path: /instance_groups/name=log-cache-blackbox/jobs/name=log-cache-blackbox/properties/log_cache_host?
            value: doppler.service.cf.internal
          - type: remove
            path: /addons/name=bosh-dns
          - type: remove
            path: /releases/name=bosh-dns
          - type: replace
            path: /instance_groups/name=log-cache-blackbox/jobs/name=log-cache-blackbox/properties/datadog/api_key
            value: ((datadog-prod-api-key))
          EOF

          bosh \
            deploy "log-cache-release/$MANIFEST_FILE" \
            --deployment "$DEPLOYMENT_NAME" \
            --non-interactive \
            --vars-file "deployments-loggregator/$SECRETS_FILE" \
            --ops-file pws.yml
