groups:
- name: log-cache-release
  jobs:
  - release-patch-version
  - release-minor-version
  - release-major-version
  - log-cache-create-final-release
  - bump-golang
- name: log-cache-cli
  jobs:
  - log-cache-cli-bump-major
  - log-cache-cli-create-final-release

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: log-cache-cli
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-cli
    private_key: ((github-key-ci.yml/Notes/github_key))
    branch: master

- name: log-cache-cli-version
  type: semver
  source:
    initial_version: 0.0.0
    bucket: loggregator-ci-versions
    key: log-cache-cli
    access_key_id: ((release-credentials.yml/Notes/loggregator-team-s3-access-key))
    secret_access_key: ((release-credentials.yml/Notes/loggregator-team-s3-secret-key))

- name: log-cache-release-version
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache
    access_key_id: ((release-credentials.yml/Notes/loggregator-team-s3-access-key))
    secret_access_key: ((release-credentials.yml/Notes/loggregator-team-s3-secret-key))

- name: log-cache-release-version-major
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache
    access_key_id: ((release-credentials.yml/Notes/loggregator-team-s3-access-key))
    secret_access_key: ((release-credentials.yml/Notes/loggregator-team-s3-secret-key))

- name: log-cache-release-version-minor
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache
    access_key_id: ((release-credentials.yml/Notes/loggregator-team-s3-access-key))
    secret_access_key: ((release-credentials.yml/Notes/loggregator-team-s3-secret-key))

- name: log-cache-release-version-patch
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache
    access_key_id: ((release-credentials.yml/Notes/loggregator-team-s3-access-key))
    secret_access_key: ((release-credentials.yml/Notes/loggregator-team-s3-secret-key))

- name: log-cache-cli-github-release-drafts
  type: github-release
  source:
    user: cloudfoundry
    repository: log-cache-cli
    access_token: ((github-key-ci.yml/Notes/github-access-token))
    drafts: true

- name: log-cache-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-ci
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: log-cache-release-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: develop
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: log-cache-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: log-cache-github-release-drafts
  type: github-release
  source:
    user: cloudfoundry
    repository: log-cache-release
    access_token: ((github-key-ci.yml/Notes/github-access-token))
    drafts: true

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-ci.yml/Notes/slack_alert_webhook_url))

shared:
  - &send-release-alert-message
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_alert_channel))
        text_file: messages/success.txt

jobs:
- name: release-patch-version
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks-image
    - get: log-cache-ci
    - get: log-cache-release-version-patch
      params: {bump: patch}
  - task: create-message
    file: log-cache-ci/tasks/alert-message-release-start/task.yml
    image: cf-deployment-concourse-tasks-image
    input_mapping:
      version: log-cache-release-version-patch
    params:
      LEVEL: patch
  on_success:
    do:
    - put: log-cache-release-version
      params: {file: log-cache-release-version-patch/version}
    - put: log-cache-release-version-patch
      params: {file: log-cache-release-version-patch/version}
    - <<: *send-release-alert-message

- name: release-minor-version
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks-image
    - get: log-cache-ci
    - get: log-cache-release-version-minor
      params: {bump: minor}
  - task: create-message
    file: log-cache-ci/tasks/alert-message-release-start/task.yml
    image: cf-deployment-concourse-tasks-image
    input_mapping:
      version: log-cache-release-version-minor
    params:
      LEVEL: minor
  on_success:
    do:
    - put: log-cache-release-version
      params: {file: log-cache-release-version-minor/version}
    - put: log-cache-release-version-minor
      params: {file: log-cache-release-version-minor/version}
    - <<: *send-release-alert-message

- name: release-major-version
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks-image
    - get: log-cache-ci
    - get: log-cache-release-version-major
      params: {bump: major}
  - task: create-message
    file: log-cache-ci/tasks/alert-message-release-start/task.yml
    image: cf-deployment-concourse-tasks-image
    input_mapping:
      version: log-cache-release-version-major
    params:
      LEVEL: major
  on_success:
    do:
    - put: log-cache-release-version
      params: {file: log-cache-release-version-major/version}
    - put: log-cache-release-version-major
      params: {file: log-cache-release-version-major/version}
    - <<: *send-release-alert-message

- name: log-cache-create-final-release
  serial: true
  disable_manual_trigger: true
  plan:
  - get: log-cache-release-version-patch
    trigger: true
    passed: [release-patch-version]
  - get: log-cache-release-version-minor
    trigger: true
    passed: [release-minor-version]
  - get: log-cache-release-version-major
    trigger: true
    passed: [release-major-version]
  - aggregate:
    - get: log-cache-release-develop
    - get: log-cache-release-master
    - get: log-cache-ci
    - get: log-cache-release-version
  - do:
    - task: update-version-artifact
      file: log-cache-ci/tasks/update-version-artifact/task.yml
    - put: log-cache-release-master
      params:
        repository: log-cache-release-master-modified
        rebase: false
    - put: log-cache-release-develop
      params:
        repository: log-cache-release-develop-modified
        rebase: false

  - do:
    - task: create-final-release
      file: log-cache-ci/tasks/create-final-release/task.yml
      params:
        S3_ACCESS_KEY: ((release-credentials.yml/Notes/loggregator-team-s3-access-key))
        S3_SECRET_KEY: ((release-credentials.yml/Notes/loggregator-team-s3-secret-key))
    - put: log-cache-release-master
      params:
        repository: log-cache-release-master-modified
        rebase: false
    - put: log-cache-release-develop
      params:
        repository: log-cache-release-develop-modified
        rebase: false
    - put: log-cache-github-release-drafts
      params:
        name: github-release/name
        tag: github-release/tag
        body: github-release/body
        globs:
        - github-release/*.tgz
  on_success:
    do:
    - task: create-message
      file: log-cache-ci/tasks/alert-message-release-end/task.yml
      input_mapping:
        version: log-cache-release-version
    - <<: *send-release-alert-message

- name: bump-golang
  serial: true
  plan:
  - aggregate:
    - get: log-cache-release-develop
  - task: download-go
    file: log-cache-ci/tasks/download-golang/task.yml
    params:
      VERSION: &golang-version 1.10.3
  - do:
    - task: bump-log-cache-release
      file: log-cache-ci/tasks/bump-golang/task.yml
      input_mapping:
        release-repo: log-cache-release-develop
      output_mapping:
        updated-release-repo: updated-log-cache-release
      params:
        VERSION: *golang-version
        ACCESS_KEY_ID: ((release-credentials.yml/Notes/loggregator-team-s3-access-key))
        SECRET_ACCESS_KEY: ((release-credentials.yml/Notes/loggregator-team-s3-secret-key))
        BUCKET_NAME: log-cache-release-blobs
    - task: commit-log-cache-release
      file: log-cache-ci/tasks/commit/task.yml
      input_mapping:
        release-repo: updated-log-cache-release
      output_mapping:
        committed-repo: committed-log-cache-release
      params:
        COMMIT_MESSAGE: "Bump golang version"
    - put: log-cache-release-develop
      params:
        repository: committed-log-cache-release
        rebase: false

- name: log-cache-cli-bump-major
  serial: true
  plan:
  - put: log-cache-cli-version
    params: {bump: major}

- name: log-cache-cli-create-final-release
  serial: true
  plan:
  - aggregate:
    - get: log-cache-cli
    - get: log-cache-cli-version
      params: {bump: minor}
  - task: create-binaries
    config:
      image_resource:
        type: docker-image
        source:
          repository: loggregator/base
      platform: linux
      inputs:
      - name: log-cache-cli
      - name: log-cache-cli-version
      outputs:
      - name: output-repo
      - name: github-release
      - name: version
      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash
            set -ex

            # establish version/tag strings
            semver="$(cat log-cache-cli-version/version)"
            cp log-cache-cli-version/version version

            # build version to inject into build with ldflags
            IFS="." read -r -a version_parts <<< $semver
            version="{\"Major\":${version_parts[0]},\"Minor\":${version_parts[1]},\"Build\":${version_parts[2]}}"

            # write out github release files
            echo "log cache cli $semver" > github-release/name
            echo "v$semver" > github-release/tag
            echo "TBD" > github-release/body
            cp -R log-cache-cli/. output-repo

            export WORKSPACE="$PWD"

            mkdir -p go
            pushd go
              export GOPATH="$PWD"
              mkdir -p src/code.cloudfoundry.org
              cp -R "$WORKSPACE/log-cache-cli/" src/code.cloudfoundry.org
              GOOS=linux go get -d ./...
              GOOS=darwin go get -d ./...
              GOOS=windows go get -d ./...
            popd

            mkdir github-release/builds
            pushd "$GOPATH/src/code.cloudfoundry.org/log-cache-cli/cmd/cf-lc-plugin"
              GOOS=linux go build -ldflags "-X main.version=$version" -o $WORKSPACE/github-release/builds/log-cache-cf-plugin-linux
              GOOS=darwin go build -ldflags "-X main.version=$version" -o $WORKSPACE/github-release/builds/log-cache-cf-plugin-darwin
              GOOS=windows go build -ldflags "-X main.version=$version" -o $WORKSPACE/github-release/builds/log-cache-cf-plugin-windows
            popd
            pushd "$GOPATH/src/code.cloudfoundry.org/log-cache-cli/cmd/lc"
              GOOS=linux go build -ldflags "-X main.version=$version" -o $WORKSPACE/github-release/builds/log-cache-linux
              GOOS=darwin go build -ldflags "-X main.version=$version" -o $WORKSPACE/github-release/builds/log-cache-darwin
              GOOS=windows go build -ldflags "-X main.version=$version" -o $WORKSPACE/github-release/builds/log-cache-windows
            popd

  - put: log-cache-cli
    params:
      repository: output-repo
      rebase: false
      tag: github-release/tag
  - put: log-cache-cli-github-release-drafts
    params:
      name: github-release/name
      tag: github-release/tag
      body: github-release/body
      globs:
      - github-release/builds/*
  - put: log-cache-cli-version
    params:
      file: version/version
