resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: log-cache-release-version
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache-temp
    access_key_id: {{loggregator-team-s3-access-key}}
    secret_access_key: {{loggregator-team-s3-secret-key}}

- name: log-cache-release-version-major
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache-temp
    access_key_id: {{loggregator-team-s3-access-key}}
    secret_access_key: {{loggregator-team-s3-secret-key}}

- name: log-cache-release-version-minor
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache-temp
    access_key_id: {{loggregator-team-s3-access-key}}
    secret_access_key: {{loggregator-team-s3-secret-key}}

- name: log-cache-release-version-patch
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache-temp
    access_key_id: {{loggregator-team-s3-access-key}}
    secret_access_key: {{loggregator-team-s3-secret-key}}

- name: log-cache-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-ci
    branch: mg-hw-temp-release
    private_key: {{github_key}}

- name: log-cache-release-develop
  type: git
  source:
    uri: git@github.com:hdub2/log-cache-release
    branch: develop
    private_key: {{github_key}}

- name: log-cache-release-master
  type: git
  source:
    uri: git@github.com:hdub2/log-cache-release
    branch: master
    private_key: {{github_key}}

- name: log-cache-github-release-drafts
  type: github-release
  source:
    user: hdub2
    repository: log-cache-release
    access_token: {{github-access-token}}
    drafts: true

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack_alert_webhook_url}}

shared:
  - &alert-message-release
    do:
    - put: slack-alert
      params:
        silent: true
        username: {{slack_alert_username}}
        icon_url: {{slack_alert_icon_url}}
        channel: {{slack_alert_channel}}
        text_file: messages/success.txt

jobs:
- name: release-patch-version
  plan:
  - aggregate:
    - get: log-cache-ci
    - get: log-cache-release-version-patch
      params: {bump: patch}
  - task: create-message
    file: log-cache-ci/tasks/alert-message-release/task.yml
    input_mapping:
      version: log-cache-release-version-patch
    params:
      LEVEL: patch
  on_success:
    do:
    - put: log-cache-release-version
      params: {file: log-cache-release-version-patch/version}
    - put: log-cache-release-version-patch
      params: {file: log-cache-release-version-patch/version}
    - <<: *alert-message-release

- name: release-minor-version
  plan:
  - aggregate:
    - get: log-cache-ci
    - get: log-cache-release-version-minor
      params: {bump: minor}
  - task: create-message
    file: log-cache-ci/tasks/alert-message-release/task.yml
    input_mapping:
      version: log-cache-release-version-minor
    params:
      LEVEL: minor
  on_success:
    do:
    - put: log-cache-release-version
      params: {file: log-cache-release-version-minor/version}
    - put: log-cache-release-version-minor
      params: {file: log-cache-release-version-minor/version}
    - <<: *alert-message-release

- name: release-major-version
  plan:
  - aggregate:
    - get: log-cache-ci
    - get: log-cache-release-version-major
      params: {bump: major}
  - task: create-message
    file: log-cache-ci/tasks/alert-message-release/task.yml
    input_mapping:
      version: log-cache-release-version-major
    params:
      LEVEL: major
  on_success:
    do:
    - put: log-cache-release-version
      params: {file: log-cache-release-version-major/version}
    - put: log-cache-release-version-major
      params: {file: log-cache-release-version-major/version}
    - <<: *alert-message-release

- name: log-cache-create-final-release
  serial: true
  disable_manual_trigger: true
  plan:
  - get: log-cache-release-version-patch
    trigger: true
    passed: [release-patch-version]
  - get: log-cache-release-version-minor
    trigger: true
    passed: [release-minor-version]
  - get: log-cache-release-version-major
    trigger: true
    passed: [release-major-version]
  - aggregate:
    - get: log-cache-release-develop
    - get: log-cache-release-master
    - get: log-cache-ci
    - get: log-cache-release-version
  - do:
    - task: update-version-artifact
      file: log-cache-ci/tasks/update-version-artifact/task.yml
    - put: log-cache-release-master
      params:
        repository: log-cache-release-master-modified
        rebase: false
    - put: log-cache-release-develop
      params:
        repository: log-cache-release-develop-modified
        rebase: false

  - do:
    - task: create-final-release
      file: log-cache-ci/tasks/create-final-release/task.yml
      params:
        S3_ACCESS_KEY: {{loggregator-team-s3-access-key}}
        S3_SECRET_KEY: {{loggregator-team-s3-secret-key}}
    - put: log-cache-release-master
      params:
        repository: log-cache-release-master-modified
        rebase: false
    - put: log-cache-release-develop
      params:
        repository: log-cache-release-develop-modified
        rebase: false
    - put: log-cache-github-release-drafts
      params:
        name: github-release/name
        tag: github-release/tag
        body: github-release/body
        globs:
        - github-release/*.tgz
