---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: pcf-observability-ci-image
    type: docker-image
    source:
      repository: gcr.io/cf-denver/pcf-observability-ci
      username: _json_key
      password: ((release-credentials.yml/Notes/gcp-service-account-key))

  - name: log-cache-ci
    type: git
    source:
      uri: git@github.com:cloudfoundry/log-cache-ci
      branch: rh-mg-upload-dev-release
      private_key: ((github-key-ci.yml/Notes/github_key))

  - name: log-cache-deployments
    type: git
    source:
      uri: git@github.com:cloudfoundry/log-cache-deployments
      branch: master
      private_key: ((github-key-ci.yml/Notes/github_key))

  - name: p-o11y-store-src
    type: git
    source:
      uri: git@github.com:pivotal/p-o11y-store
      branch: master
      private_key: ((github-key-ci.yml/Notes/github_key))

  - name: metric-store-release
    type: git
    source:
      uri: git@github.com:pivotal/metric-store-release
      branch: rh-mg-upload-dev-release
      private_key: ((github-key-ci.yml/Notes/github_key))

  - name: p-metric-store-version
    type: semver
    source:
      driver: gcs
      bucket: log-cache-ci-versions
      key: metric-store-release-acceptance-tile
      json_key: ((release-credentials.yml/Notes/gcp-service-account-key))
      initial_version: 0.0.0

  - name: concourse-tasks
    type: git
    source:
      uri: https://github.com/pivotal-cf/concourse-tasks
      branch: master

  - name: bobble
    type: git
    source:
      uri: git@github.com:pivotal/bobble
      branch: master
      private_key: ((github-key-ci.yml/Notes/github_key))

  - name: metric-store-dev-release
    type: gcs-resource
    source:
      bucket: log-cache-ci-notifications
      json_key: ((release-credentials.yml/Notes/gcp-service-account-key))
      regexp: metric-store-dev-releases/release-(.*).tgz

jobs:
  - name: "🥓 Bake and Install Tile 🥓"
    serial: true
    plan:
      - aggregate:
        - get: bobble
        - get: concourse-tasks
        - get: p-o11y-store-src
        - get: log-cache-ci
        - get: log-cache-deployments
        - get: metric-store-release
        - get: p-metric-store-version
          params:
            pre: build
        - get: metric-store-dev-release
          trigger: true
        - get: pcf-observability-ci-image
        attempts: 3
      - task: "prepare deployment environment"
        file: bobble/ci-tasks/prepare-environment/prepare-environment.yml
        input_mapping:
          src: log-cache-deployments
        params:
          ENV_PATH: gcp/optimus
      - task: "bake and install"
        image: pcf-observability-ci-image
        file: log-cache-ci/tasks/bake_and_install/task.yml
        input_mapping:
          deployment-tools: bobble
          tile-src: p-o11y-store-src
          tile-config: log-cache-ci
          tile-version: p-metric-store-version
        params:
          OPSMAN_USER: ((log-cache-ops-manager/Username))
          OPSMAN_PASSWORD: ((log-cache-ops-manager/Password))
          STEMCELL_URL: https://s3.amazonaws.com/bosh-gce-light-stemcells/light-bosh-stemcell-170.16-google-kvm-ubuntu-xenial-go_agent.tgz
          STEMCELL_SHA: 9bb3663ee35f795f466a65a5fb185c4b650049cd
          PRODUCT_CONFIG_PATH: tile-config/tile/metric-store-config.yml
    ensure:
      put: p-metric-store-version
      params:
        file: p-metric-store-version/version
