image_resource:
  type: docker-image
  source:
    repository: logcache/base
platform: linux

inputs:
- name: release-master
- name: release-develop
- name: release-version
- name: log-cache-ci

outputs:
- name: release-tarball
- name: release-master-modified
- name: release-develop-modified

run:
  path: log-cache-ci/tasks/create-private-release/task

params:
  JSON_KEY:
