resources:
- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.20.0

- name: log-cache-deployments
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-deployments
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: log-cache-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: develop
    private_key: ((github-key-ci.yml/Notes/github_key))

jobs:
- name: log-cache-blackbox-deploy
  serial: true
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks-image
    - get: log-cache-release
    - get: log-cache-deployments

  - aggregate:
    - task: upload-log-cache
      image: cf-deployment-concourse-tasks-image
      config:
        platform: linux
        inputs:
        - name: log-cache-release
        params:
          BOSH_CLIENT: ((bosh-admin-client.username))
          BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
          BOSH_CA_CERT: ((bosh-ca-cert.certificate))
          BOSH_ENVIRONMENT: bosh.run.pivotal.io
        run:
          path: bash
          args:
          - -c
          - |
            #!/bin/bash
            set -eux

            pushd log-cache-release
              bosh create-release
              bosh upload-release --rebase
            popd

  - task: log-cache-blackbox-deploy
    image: cf-deployment-concourse-tasks-image
    config:
      platform: linux
      inputs:
      - name: log-cache-release
      - name: log-cache-deployments
      params:
        DEPLOYMENT_NAME: log-cache-blackbox
        MANIFEST_FILE: manifests/log-cache-blackbox.yml
        SECRETS_FILE: shared-secrets.yml
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        UAA_CLIENT: ((pws-datadog-forwarder-client/Notes/client_id))
        UAA_CLIENT_SECRET: ((pws-datadog-forwarder-client/Notes/client_secret))
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          cat <<EOT >> on-the-fly.yml
          - type: remove
            path: /releases/name=bpm
          - type: remove
            path: /instance_groups/name=log-cache-blackbox/jobs/name=bpm
          - type: replace
            path: /instance_groups/name=log-cache-blackbox/networks
            value: [{name: pws-cf}]
          - type: replace
            path: /instance_groups/name=log-cache-blackbox/azs
            value: [z2]
          - type: replace
            path: /instance_groups/name=log-cache-blackbox/jobs/name=log-cache-blackbox/consumes
            value:
              log-cache: {from: log-cache, deployment: cf-cfapps-io2}
              cloud_controller: {from: cloud_controller, deployment: cf-cfapps-io2}
          - type: replace
            path: /instance_groups/name=log-cache-blackbox/jobs/name=log-cache-blackbox/properties?
            value:
              cf_blackbox:
                enabled: true
                client_id: $UAA_CLIENT
                client_secret: $UAA_CLIENT_SECRET
          EOT

          bosh \
            deploy "log-cache-release/$MANIFEST_FILE" \
            --deployment "$DEPLOYMENT_NAME" \
            --non-interactive \
            --ops-file on-the-fly.yml
