image_resource:
  type: docker-image
  source:
    repository: logcache/base
platform: linux

inputs:
- name: log-cache-release-master
- name: log-cache-release-develop
- name: log-cache-release-version
- name: log-cache-ci

outputs:
- name: release-tarball
- name: log-cache-release-master-modified
- name: log-cache-release-develop-modified

run:
  path: log-cache-ci/tasks/create-final-release/task

params:
  JSON_KEY:
