---
platform: linux

inputs:
  - name: log-cache-ci
  - name: p-metric-store-release-master
  - name: stemcell
  - name: bpm-release
  - name: cf-routing-release
  - name: loggregator-agent-release
  - name: release-version
  - name: p-metric-store-final-bosh-release
  - name: oss-metric-store-final-bosh-release

outputs:
  - name: baked-tile

params:
  TILE_NAME: metric-store

run:
  path: log-cache-ci/tasks/tile_bake_final/task
