---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
  - name: log-cache-ci
  - name: this-version
  - name: main-version

outputs:
  - name: new-main-version

run:
  path: log-cache-ci/tasks/sync_versions/patch
