---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.26.0

inputs:
  - name: log-cache-ci
  - name: certs

outputs:
  - name: archived-certs

run:
  path: log-cache-ci/tasks/generate-certs/archive-certs
