---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v3.19.0

inputs:
- name: log-cache-ci # - This repo
- name: release-repo

outputs:
- name: committed-repo

run:
  path: ../log-cache-ci/tasks/commit-with-shortlog/task
  dir: committed-repo

params:
  # Required. The paths to commit.
  PATHS:
