platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.20.0

inputs:
- name: log-cache-ci # This repo
- name: bbl-state      # The BBL state repository
- name: cf-deployment-concourse-tasks

run:
  path: log-cache-ci/tasks/run-errand/task

params:
  # - Required
  # - Directory where bbl state is stored.
  # - Relative to bbl-state input.
  BBL_STATE_DIR:

  # - Required
  # - Name of the deployment to run the errand on.
  DEPLOYMENT_NAME:

  # - Required
  # - Name of the errand to run.
  ERRAND:

  # - Optional
  # - Run errand with --keep-alive
  KEEP_ALIVE: false
