---
platform: linux

inputs:
- name: log-cache-ci
- name: bosh-dev-release-dir
- name: bosh-dev-release-version
- name: metric-store-release

outputs:
- name: metric-store-dev-release
- name: bosh-new-dev-release-version

run:
  path: log-cache-ci/tasks/create-dev-release/task

params:
  JSON_KEY:
