---
platform: linux

caches:
- path: bosh-release-dir/blobs

inputs:
- name: log-cache-ci # - This repo
- name: bbl-state  # - The Director's `bbl-state.json`
  optional: true

run:
  path: log-cache-ci/tasks/cleanup-release/task

params:
  # - Optional; must provide this OR the BOSH_* variables below
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - Defaults to the root of the `bbl-state` input
  BBL_STATE_DIR:

  # - Optional
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  JSON_KEY:
  RELEASE_NAME:
