#!/bin/bash -euf
echo "running build and install"
export RELEASE_VERSION=$(cat tile-version/version)

mkdir -p releases
set +f
mv metric-store-dev-release/*.tgz releases
mv p-prom-telegraf-dummy-release/*.tgz releases
mv p-prom-prometheus-dummy-release/*.tgz releases
mv p-prom-cf-auth-proxy-dummy-release/*.tgz releases
mv p-prom-thanos-dummy-release/*.tgz releases
set -f

TILE_FILE=baked_tile/o11y-store-${RELEASE_VERSION}.pivotal

kiln bake \
    --version "$RELEASE_VERSION" \
    --metadata tile-src/metadata.yml \
    --icon tile-src/icon.png \
    --releases-directory releases \
    --jobs-directory metric-store-release/tile/jobs \
    --instance-groups-directory metric-store-release/tile/instance_groups \
    --forms-directory metric-store-release/tile/forms \
    --bosh-variables-directory metric-store-release/tile/variables \
    --output-file ${TILE_FILE}

echo "Freshly baked tile 🍞: ${TILE_FILE}"

# source environment/environment.sh
# source deployment-tools/prelude.sh
# source deployment-tools/omg.sh

# stemcell_filename=$(download-product ${STEMCELL_URL})

# omg upload-product --product ${baked_tile_dir}/${TILE_NAME}-${RELEASE_VERSION}.pivotal
# omg stage-product --product-name "observability-store" --product-version ${RELEASE_VERSION}
# omg configure-product --config ${PRODUCT_CONFIG_PATH}
# omg upload-stemcell --stemcell ${stemcell_filename} --floating true --shasum ${STEMCELL_SHA}
# omg apply-changes --product-name "observability-store"
